# Generated by Django 2.0.5 on 2019-05-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.URLField()),
                ('price', models.CharField(max_length=8)),
                ('stock', models.CharField(max_length=4)),
                ('product_description', models.TextField()),
                ('upc', models.CharField(max_length=20)),
            ],
        ),
    ]
